monolog:
    handlers:
        main:
            type: stream
            path: 'php://stderr'
            level: info

when@test:
    monolog:
        handlers:
            main:
                type: test
                level: debug
